#!/bin/bash

cd capi
./bob $@
cd ..

rm -rf nebdist
mkdir -p nebdist
cp *.py nebdist
cp -r nebfiles nebdist/nebfiles
cp -r assets nebdist/assets

cp capi/nebcapi.dylib nebdist/nebcapi.dylib

if [ $# -ge 1 ]; then #len(args) >= 1
    if [ $1 == "testneb" ]; then
        python nebdist/desktop_main.py
    fi
fi